// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expenses.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (id, user_id, description, amount_cents, category, spent_on)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, description, amount_cents, category, spent_on, created_at, updated_at
`

type CreateExpenseParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Description string
	AmountCents int64
	Category    ExpenseCategory
	SpentOn     time.Time
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.ID,
		arg.UserID,
		arg.Description,
		arg.AmountCents,
		arg.Category,
		arg.SpentOn,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Description,
		&i.AmountCents,
		&i.Category,
		&i.SpentOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :execrows
DELETE FROM expenses
WHERE id = $1 AND user_id = $2
`

type DeleteExpenseParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteExpense(ctx context.Context, arg DeleteExpenseParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpense, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getExpense = `-- name: GetExpense :one
SELECT id, user_id, description, amount_cents, category, spent_on, created_at, updated_at
FROM expenses
WHERE id = $1 AND user_id = $2
`

type GetExpenseParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetExpense(ctx context.Context, arg GetExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, getExpense, arg.ID, arg.UserID)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Description,
		&i.AmountCents,
		&i.Category,
		&i.SpentOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpenses = `-- name: ListExpenses :many
SELECT id, user_id, description, amount_cents, category, spent_on, created_at, updated_at
FROM expenses
WHERE user_id = $1
  AND ($2::date IS NULL OR spent_on >= $2)
  AND ($3::date IS NULL OR spent_on <= $3)
  AND ($4::expense_category IS NULL OR category = $4)
  AND (
      $5::date IS NULL
      OR (spent_on, id) < ($5, $6::uuid)
  )
ORDER BY spent_on DESC, id DESC
LIMIT $7
`

type ListExpensesParams struct {
	UserID        uuid.UUID
	FromDate      *time.Time
	ToDate        *time.Time
	Category      NullExpenseCategory
	CursorSpentOn *time.Time
	CursorID      *uuid.UUID
	PageSize      int32
}

func (q *Queries) ListExpenses(ctx context.Context, arg ListExpensesParams) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpenses,
		arg.UserID,
		arg.FromDate,
		arg.ToDate,
		arg.Category,
		arg.CursorSpentOn,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Expense{}
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Description,
			&i.AmountCents,
			&i.Category,
			&i.SpentOn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses
SET description  = $3,
    amount_cents = $4,
    category     = $5,
    spent_on     = $6,
    updated_at   = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, description, amount_cents, category, spent_on, created_at, updated_at
`

type UpdateExpenseParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Description string
	AmountCents int64
	Category    ExpenseCategory
	SpentOn     time.Time
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.ID,
		arg.UserID,
		arg.Description,
		arg.AmountCents,
		arg.Category,
		arg.SpentOn,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Description,
		&i.AmountCents,
		&i.Category,
		&i.SpentOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
