// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type ExpenseCategory string

const (
	ExpenseCategoryGroceries   ExpenseCategory = "groceries"
	ExpenseCategoryLeisure     ExpenseCategory = "leisure"
	ExpenseCategoryElectronics ExpenseCategory = "electronics"
	ExpenseCategoryUtilities   ExpenseCategory = "utilities"
	ExpenseCategoryClothing    ExpenseCategory = "clothing"
	ExpenseCategoryHealth      ExpenseCategory = "health"
	ExpenseCategoryOthers      ExpenseCategory = "others"
)

func (e *ExpenseCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExpenseCategory(s)
	case string:
		*e = ExpenseCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for ExpenseCategory: %T", src)
	}
	return nil
}

type NullExpenseCategory struct {
	ExpenseCategory ExpenseCategory
	Valid           bool // Valid is true if ExpenseCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExpenseCategory) Scan(value interface{}) error {
	if value == nil {
		ns.ExpenseCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExpenseCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExpenseCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExpenseCategory), nil
}

func (e ExpenseCategory) Valid() bool {
	switch e {
	case ExpenseCategoryGroceries,
		ExpenseCategoryLeisure,
		ExpenseCategoryElectronics,
		ExpenseCategoryUtilities,
		ExpenseCategoryClothing,
		ExpenseCategoryHealth,
		ExpenseCategoryOthers:
		return true
	}
	return false
}

type Expense struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Description string
	AmountCents int64
	Category    ExpenseCategory
	SpentOn     time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}
